### ISSUE TITLE
[讨论]ipv6 支持

### ISSUE THREAD

**Issue by oliverhu** [aofei/ladder-ios#16]
最近也在了解shadowsocks，NEkit，好奇一下这里不支持ipv6的原因是什么？和NEkit不支持ipv6有关系吗，还有为啥要移除对NEKit的依赖？

**Comment by sheng** [comment]
有人提出来了，那我就好好解释一下吧。

既然这个 Issue 是关于 `IPv6` 支持的讨论，那我就先说一下 `IPv6` 相关的吧。是的，这里不（完全）支持 `IPv6` 是跟 `NEKit` 有关，我查看了一下，在前几个月 `NEKit` 里有人还就这个问题讨论过，所以它还是并没有完全支持 `IPv6` 的，具体“不完全”在哪里我是没有深究过的，因为 `IPv6` 对我暂时没有太大的吸引力，如果你精力和条件允许的话可以去研究研究。

接下来说 `No longer rely on the NEKit to implement the Shadowsocks protocol` 这个 TODO 项。

首先，需要说明的是我为什么要用 `NEKit`。在我编写[“沉浸式无墙体验”](https://aofei.org/posts/2018-04-05-immersive-wallless-experience)这篇文章的时候，我同时也在开发着这款项目（本来是打算只给我自己还有我的女朋友用的）。虽然这款项目是编写文章的动机，但毫无疑问这款项目只是为了给出一个针对文章中提出的理念的实现样例而已（就像项目描述里所说的那样），所以需要**尽快开发出来**（总不能让人觉得我光说不做不是）。而且可以看到这个项目的描述里压根儿就没有提到 `Shadowsocks`，是因为我最开始想到解决代理的途径并不是 `Shadowsocks`（所以我才并没有把项目命名成类似“shadowsocks-ios”这种），虽然我对 @clowwindy 提出的这个 `Shadowsocks` 研究得并不深入，但由于它确实已经相当成熟了，而且很容易搭建服务器环境（网上傻瓜式教程一堆），所以也就没有必要再考虑别的了。

`NEKit` 的确很酷，就像我上面提到的，它可以让我把这个项目“尽快开发出来”。但不可否认的是因为依赖它也的确产生了一些问题，比如你可以看到 #3、#6、#8 还有 #12 里都有朋友提到。也有一些朋友发邮件问我像是怎么解决网络环境切换（比如 `4G` 到 `Wi-Fi` 这种）导致的网络不通的问题，我之前一直以为我在开发的时候已经解决了这个问题，但事实却是虽然我身边的人没遇到但总有其他人可能遇到。

要摆脱对 `NEKit` 的依赖还有一方面原因，`NEKit` 并不是一个单纯的为了解决 `Shadowsocks` 客户端问题而生的项目，就像它的名字一样“**N**etwork **E**xtension **Kit**”，它是为了打造出苹果的 `NetworkExtension` 框架的一个套装工具。这也就意味着它里面会存在很多这个项目不需要的东西，增加了一些不必要的项目体积。而且由于依赖了 `NEKit`，我并不能解决类似 #6 和 #12 提出的那种问题。

如果摆脱了对 `NEKit` 的依赖也就是自己实现一个 `Shadowsocks` 客户端的话，那将会解决很多很多问题（至少有解决的可能性了）。而且我也一直有这个打算，也不时在研究着，比如可以看到 `NEKit` 只出现在了 [PacketTunnel/Shadowsocks.swift](https://github.com/sheng/ladder-ios/blob/1f8cd9c8206b2b4718ed73120124db0b968473e6/PacketTunnel/Shadowsocks.swift) 里就是为了方便我移除，只是时间和精力上都不允许我投入太多在这个项目上（现在大多只是缝缝补补而已）。但是放心，我肯定会干掉这个 TODO 项的。

**Comment by oliverhu** [comment]
是的，NEKit是个非常优秀的library，但是dependency太多了，而且没有足够的documentation，看起来好辛苦，debug也很难。找时间可以写一个简化很多的为shadowsocks ios做的的library

**Comment by sheng** [comment]
哇，如果你有时间实现一个单纯的 `Shadowsocks` 客户端库让大家来依赖是最好不过的了，以你的实力我就可以放心地偷懒了😆。

**Comment by MatoMA** [comment]
如果只是Shadowsocks的话，直接把Outline的抽出来用就好了。（虽然不知道什么原因，最新的代码没法兼容老版本的服务器，但也有可能只是我参数没配好而已。）
