### ISSUE TITLE
执行carthage update --no-use-binaries --platform ios 就报错误

### ISSUE THREAD

**Issue by huhaifengfeng** [aofei/ladder-ios#29]
<img width="1235" alt="2018-08-02 7 59 22" src="https://user-images.githubusercontent.com/29226659/43582314-9b088806-968e-11e8-906b-dbaedd070632.png">

**Comment by sheng** [comment]
你可以参考一下 Issue #3，看看能不能找到解决方案。

**Comment by huhaifengfeng** [comment]
NEKit 依赖库 MMDB 失败

**Comment by sheng** [comment]
@huhaifengfeng 

有尝试过把项目目录中的 `Carthage` 完全移除后再重试吗？

说实话，我自己倒是还没有遇见过这个问题，你还可以试试 @841766048 给出的[解决方案](
https://github.com/sheng/ladder-ios/issues/3#issuecomment-404839334)，看看能不能行。

**Comment by huhaifengfeng** [comment]
试过删除相关文件，只留下Cartfile文件，尝试过N次这个carthage update --no-use-binaries --platform ios

**Comment by huhaifengfeng** [comment]
创建一个空项目，单独添加NEKit也报错不行

**Comment by BoneToy** [comment]
有个MMDB依赖下载不了。
具体情况可以在日志中找到无法下载或解压的命令位置。
最好是给终端设置代理环境，然后才能正常下载依赖。

**Comment by chzy** [comment]
> 你可以参考一下 Issue #3，看看能不能找到解决方案。
*** Building scheme "Eureka" in Eureka.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka/Eureka.xcworkspace -scheme Eureka -configuration Release -derivedDataPath /Users/Chzy/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Eureka/4.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/47/94q4j9p90wb60v8r10vnb5kr0000gn/T/Eureka SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka)


看log打印 是/Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka/Source/Core/Cell.swift:40:58: error: 'CellStyle' is not a member type of 'UITableViewCell'
    public required override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
                                         ~~~~~~~~~~~~~~~ ^
/Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka/Source/Core/Cell.swift:40:30: error: initializer does not override a designated initializer from its superclass
    public required override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
                    ~~~~~~~~ ^
/Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka/Source/Core/Cell.swift:109:49: error: 'CellStyle' is not a member type of 'UITableViewCell'
    required public init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
                                ~~~~~~~~~~~~~~~ ^
/Users/Chzy/Desktop/ladder-ios/Carthage/Checkouts/Eureka/Source/Rows/PickerInlineRow.swift:91:35: error: type 'UITableView' has no member 'automaticDimension'
        inlineRow.cell.height = { UITableView.automaticDimension }
请问多次carthage update --no-use-binaries --platform ios 行不通呀

**Comment by chzy** [comment]
![17c2b659-31bf-4427-a33f-9fb35f903b68](https://user-images.githubusercontent.com/14284831/46240388-3c318d00-c3d9-11e8-8e01-153b35e8b85f.png)
![6b5e9f4f-8692-4900-97cf-de5ddb579567](https://user-images.githubusercontent.com/14284831/46240394-50758a00-c3d9-11e8-8a21-fa4400a129b0.png)
