### ISSUE TITLE
ios12可以用吗?

### ISSUE THREAD

**Issue by piaozhx** [aofei/ladder-ios#35]
用xcode10 beta版编译报错
```
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/piaozhx/Desktop/ladder-ios/Carthage/Build/iOS/Alamofire.framework/Modules/Alamofire.swiftmodule/arm64.swiftmodule
```

**Comment by sheng** [comment]
编译依赖时记得加上 `--no-use-binaries`，否则 Carthage 会自己去查找目标项目已经编译好了的二进制文件，这个对于先行版来说倒没什么，但对于 Beta 版来说就可能会存在问题了，比如你遇到的这个就是的。

```bash
$ carthage update --no-use-binaries --platform iOS
```

**Comment by piaozhx** [comment]
重新下载编译了一遍, 还是报错, 严格按照README中的步骤执行的, 在xcode9上给ios11的手机编译正常, 在xcode10 beta4 给 ios12的手机编译就报错...
![ios12](https://user-images.githubusercontent.com/9268675/45142555-70a39600-b1eb-11e8-8c40-17a7fb5cfc6f.png)

**Comment by sheng** [comment]
我检查了一下，目前依赖的 Alamofire 版本是支持 Swift 4.2 的，所以可能是 Carthage 编译的问题了。

你可以在终端检查一下你的 xcodebuild 的版本：

```bash
$ xcodebuild -version
```

**Comment by aofei** [comment]
跟 Alamofire 无关，是 NEKit 的问题，他写的不规范，有些代码在之前的 Swift 版本里属于警告，但在最新的版本里被认为是错误了，所以编译不通过。等他修复的吧。
