### ISSUE TITLE
Missing required module 'CommonCrypto'

### ISSUE THREAD

**Issue by xingyifeng** [aofei/ladder-ios#6]
import NEKit      prompt      Missing required module 'CommonCrypto'
How do I fix it?

**Comment by sheng** [comment]
You can try the following steps:

1. Close the project (Xcode).

2. Delete the Carthage folder in the project root directory.

3. Open the terminal and enter the project root directory.

4. Re-execute `carthage update --no-use-binaries --platform ios` and wait for success.

5. After the step 4 is successful, open the project (Xcode) again to see if it can compile and run.

**Comment by xingyifeng** [comment]
我按照你说的方法试了,不行,还是报一样的错误.
其实我第一次下载之后是可以使用的,但是第二天我再次打开工程运行就不能使用了,
我试着重新下载工程 编译,但还是不可以,
这是我Xcode版本 Version 9.3 (9E145)  这是我Mac版本 10.13.4 (17E199)
这中间可能发生了什么,只记得我同事找我要xcode包,我从finder中拷贝了一份给他,其他没有操作过,谢谢

**Comment by jackrex** [comment]
project clean 一次吧，可能你升级了 swift ，编译的 swift 版本不一致，删除 Carthage 文件夹，重新 carthage update 完，重新打开项目
